@id = 4
DELETE http://localhost/api/scores/{{id}}
Accept: application/json

###
GET http://localhost/api/scores
Accept: application/json

###
POST http://localhost/api/scores
Content-Type: application/json

{
  "Names": "Illegal Score",
  "Score": 202
}

