apiVersion: v1
kind: Service
metadata:
  name: matchmaker-service
spec:
  selector:
    app: matchmaker
  ports:
    - name: matchmaker
      protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer