apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: pigeon-project-fleet
spec:
  replicas: 2
  scheduling: Packed
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  priorities:
    - type: List
      key: players
      order: Ascending
  template:
    # GameServer metadata
    metadata:
      generateName: pigeon-project-
    spec:
      ports:
        - name: default
          range: default
          portPolicy: Dynamic
          containerPort: 7000
          protocol: UDP
      health:
        disabled: false
        initialDelaySeconds: 5
        periodSeconds: 5
        failureThreshold: 3
      sdkServer:
        logLevel: Info
        grpcPort: 9357
        httpPort: 9358
      counters:
        players:
          count: 0
          capacity: 5
      lists:
      template:
        spec:
          containers:
            - name: pigeon-project-server
              image: docker.io/tp8843/pigeon-project-server
              imagePullPolicy: Always
---
apiVersion: "autoscaling.agones.dev/v1"
kind: FleetAutoscaler
metadata:
  name: fleet-autoscaler-example
spec:
  fleetName: pigeon-project-fleet
  policy:
    type: Buffer
    buffer:
      bufferSize: 4
      minReplicas: 4
      maxReplicas: 20
  sync:
    type: FixedInterval
    fixedInterval:
      seconds: 30